name: 'Test Application Startup'
description: 'Tests Spring Boot application startup with health check'

inputs:
  working-directory:
    description: 'Working directory'
    required: true
  services:
    description: 'Changed services to test'
    required: true
  health-port:
    description: 'Health check port'
    required: false
    default: '8082'
  timeout-seconds:
    description: 'Startup timeout in seconds'
    required: false
    default: '60'

runs:
  using: "composite"
  steps:
    - name: Test application startup
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        for service in ${{ inputs.services }}; do
          echo "Testing Service... [$service]"

          # 빌드된 JAR 파일 찾기
          JAR_FILE=$(find build/libs -name "*.jar" | head -n 1)
          echo "Testing JAR: $JAR_FILE"

          # 백그라운드 실행
          nohup java -Dspring.output.ansi.enabled=NEVER \
              -jar $JAR_FILE \
              --management.endpoint.health.show-details=always > app.log 2>&1 &

          APP_PID=$!
          echo "Started JAR with PID: $APP_PID"

          # 최대 N초 대기하면서 애플리케이션 시작 확인
          echo "Waiting for application to start..."

          # *** Health Check **** #
          for i in $(seq 1 ${{ inputs.timeout-seconds }}); do
            RESPONSE=$(curl -s -f http://localhost:${{ inputs.health-port }}/actuator/health || true)
            if [[ "$RESPONSE" == *"UP"* ]]; then
              echo "Application started successfully after ${i}s"
              kill $APP_PID 2>/dev/null || true
              exit 0
            fi

            # 헬스 체크 응답 결과 출력
            echo "=== Actuator Health Response ==="
            echo "$RESPONSE" | jq .
            echo "=================================="

            # 프로세스가 중간에 죽었는지 체크
            if ! kill -0 $APP_PID 2>/dev/null; then
              echo "Application process died unexpectedly"
              cat app.log
              exit 1
            fi

            # 디버깅 - 실패 원인 찾기
            if [ $((i % 10)) -eq 0 ]; then
              echo "Waiting... ($i/${{ inputs.timeout-seconds }}s)"
              echo "Last curl response: $RESPONSE"
              curl -s -o /dev/null -w "%{http_code}" http://localhost:${{ inputs.health-port }}/actuator/health || echo "Connection Refused"
              echo ""
            fi

            sleep 1
          done

          echo "Application failed to start within ${{ inputs.timeout-seconds }}s"
          cat app.log
          kill $APP_PID 2>/dev/null || true
          exit 1
        done
