name: 'Setup Java and Gradle'
description: 'Sets up JDK 21 and Gradle with caching'

inputs:
  working-directory:
    description: 'Working directory for gradle commands'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Grant execute permission for gradlew
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: chmod +x gradlew
