{
 "title": "Loki Logs - POC",
 "tags": [
  "loki",
  "logs",
  "poc"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "label_values({job=\"fluent-bit\"}, container_name)"
   },
   { "name": "level", "query": "ALL,ERROR,WARN,INFO,DEBUG" }
  ]
 },
 "panels": [
  {
   "title": "Error logs / min",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (container_name) (rate({job=\"fluent-bit\", container_name=~\"$service\"} |~ \"(?i)error\" [1m]))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Top services by ERROR (last 15m)",
   "type": "bargauge",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (container_name) (count_over_time({job=\"fluent-bit\", container_name=~\"$service\"} |~ \"(?i)error\" [15m])))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Recent logs",
   "type": "logs",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 12 },
   "targets": [
    {
     "expr": "{job=\"fluent-bit\", container_name=~\"$service\"}"
    }
   ]
  }
 ]
}