FROM quay.io/strimzi/kafka:latest-kafka-4.0.0

USER root:root
RUN mkdir -p /opt/kafka/plugins/debezium
ADD https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/3.4.0.Final/debezium-connector-postgres-3.4.0.Final-plugin.tar.gz /tmp/
RUN tar -xzf /tmp/debezium-connector-postgres-3.4.0.Final-plugin.tar.gz -C /opt/kafka/plugins/debezium --strip-components=1 && \
    rm /tmp/debezium-connector-postgres-3.4.0.Final-plugin.tar.gz

USER 1001