apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: test-rollout
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-rollout
  template:
    metadata:
      labels:
        app: test-rollout
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}