apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: monitoring
data:
  fluent-bit.conf: |-
    [SERVICE]
        Flush         1
        Daemon        Off
        Log_Level     info
        Parsers_File  parsers.conf
    
    [INPUT]
        Name              tail
        Tag               kube.var.log.containers.*
        Path              /var/log/containers/*.log
        Parser            cri
        DB                /fluent-bit/tail/flb_kube.db
        Mem_Buf_Limit     50MB
        Skip_Long_Lines   On
        Refresh_Interval  10

    [FILTER]
        Name              kubernetes
        Match             kube.var.log.containers.*
        Kube_Tag_Prefix   kube.var.log.containers.
        Kube_URL          https://kubernetes.default.svc:443
        Merge_Log         On
        Merge_Log_Key     log
        Keep_Log          Off
        Labels            On

    [FILTER]
        Name            parser
        Match           kube.var.log.containers.*
        Key_Name        log
        Parser          json
        Reserve_Data    On
    
    [OUTPUT]
        Name            loki
        Match           kube.var.log.containers.*
        Host            loki-service.monitoring.svc.cluster.local
        Uri             /loki/api/v1/push
        Port            3100
        Labels          job=fluent-bit,namespace=$kubernetes['namespace_name'],container=$kubernetes['container_name'],pod=$kubernetes['pod_name']
        Line_Format     json

  parsers.conf: |-
    [PARSER]
        Name        cri
        Format      regex
        Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L

    [PARSER]
        Name        json
        Format      json
        Time_Key    timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%L
